CREATE TABLE animal (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  account_id BIGINT NOT NULL,
  ranch_id BIGINT NOT NULL,
  lot_id BIGINT NULL,
  internal_tag VARCHAR(40) NOT NULL,
  official_tag VARCHAR(60) NULL,
  rfid VARCHAR(40) NULL,
  name VARCHAR(80) NULL,
  sex ENUM('FEMALE','MALE') NOT NULL,
  birth_date DATE NULL,
  birth_date_estimated BOOLEAN NOT NULL DEFAULT FALSE,
  breed_id BIGINT NOT NULL,
  purpose ENUM('BEEF','DAIRY','DUAL') NOT NULL,
  status ENUM('ACTIVE','SOLD','DEAD','MISSING','TRANSFERRED') NOT NULL DEFAULT 'ACTIVE',
  cover_photo_id BIGINT NULL,
  notes TEXT NULL,
  created_by_user_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_animal_account FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE RESTRICT,
  CONSTRAINT fk_animal_ranch FOREIGN KEY (ranch_id) REFERENCES ranch(id) ON DELETE RESTRICT,
  CONSTRAINT fk_animal_lot FOREIGN KEY (lot_id) REFERENCES lot(id) ON DELETE RESTRICT,
  CONSTRAINT fk_animal_breed FOREIGN KEY (breed_id) REFERENCES breed(id) ON DELETE RESTRICT,
  CONSTRAINT fk_animal_user FOREIGN KEY (created_by_user_id) REFERENCES app_user(id) ON DELETE RESTRICT,
  CONSTRAINT uq_animal_tag UNIQUE (account_id, internal_tag),
  CONSTRAINT uq_animal_official_tag UNIQUE (account_id, official_tag),
  INDEX ix_animal_account_ranch_lot_status (account_id, ranch_id, lot_id, status),
  INDEX ix_animal_account_breed (account_id, breed_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
