-- V7: Eventos sanitarios multi-tenant.
-- vet_visit primero para que vaccination/diagnosis/treatment puedan referenciarla.

CREATE TABLE vet_visit (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  ranch_id BIGINT NOT NULL,
  visited_at DATE NOT NULL,
  vet_name VARCHAR(160) NOT NULL,
  vet_contact VARCHAR(160) NULL,
  reason VARCHAR(300) NOT NULL,
  total_cost DECIMAL(12,2) NULL,
  notes TEXT NULL,
  created_by_user_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vet_visit_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_vet_visit_ranch FOREIGN KEY (ranch_id) REFERENCES ranch(id),
  CONSTRAINT fk_vet_visit_user FOREIGN KEY (created_by_user_id) REFERENCES app_user(id),
  INDEX ix_vet_visit_acct_ranch_date (account_id, ranch_id, visited_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE vaccination (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  animal_id BIGINT NULL,
  lot_id BIGINT NULL,
  vaccine_id BIGINT NOT NULL,
  batch_number VARCHAR(80) NULL,
  applied_at DATE NOT NULL,
  dose_ml DECIMAL(5,2) NULL,
  route ENUM('IM','SC','ORAL','INTRANASAL','TOPICAL') NULL,
  next_dose_due DATE NULL,
  cost DECIMAL(10,2) NULL,
  applied_by_user_id BIGINT NULL,
  vet_visit_id BIGINT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vaccination_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_vaccination_animal FOREIGN KEY (animal_id) REFERENCES animal(id),
  CONSTRAINT fk_vaccination_lot FOREIGN KEY (lot_id) REFERENCES lot(id),
  CONSTRAINT fk_vaccination_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccine(id),
  CONSTRAINT fk_vaccination_user FOREIGN KEY (applied_by_user_id) REFERENCES app_user(id),
  CONSTRAINT fk_vaccination_visit FOREIGN KEY (vet_visit_id) REFERENCES vet_visit(id),
  INDEX ix_vacc_acct_animal_date (account_id, animal_id, applied_at),
  INDEX ix_vacc_acct_lot_date (account_id, lot_id, applied_at),
  INDEX ix_vacc_next_dose (account_id, next_dose_due)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE diagnosis (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  animal_id BIGINT NOT NULL,
  disease_id BIGINT NOT NULL,
  diagnosed_at DATE NOT NULL,
  severity ENUM('LOW','MEDIUM','HIGH') NOT NULL DEFAULT 'MEDIUM',
  symptoms VARCHAR(500) NULL,
  status ENUM('ACTIVE','RECOVERED','CHRONIC','DECEASED') NOT NULL DEFAULT 'ACTIVE',
  resolved_at DATE NULL,
  diagnosed_by_user_id BIGINT NULL,
  vet_visit_id BIGINT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_diag_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_diag_animal FOREIGN KEY (animal_id) REFERENCES animal(id),
  CONSTRAINT fk_diag_disease FOREIGN KEY (disease_id) REFERENCES disease(id),
  CONSTRAINT fk_diag_user FOREIGN KEY (diagnosed_by_user_id) REFERENCES app_user(id),
  CONSTRAINT fk_diag_visit FOREIGN KEY (vet_visit_id) REFERENCES vet_visit(id),
  INDEX ix_diag_acct_animal_date (account_id, animal_id, diagnosed_at),
  INDEX ix_diag_acct_status_date (account_id, status, diagnosed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE treatment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  animal_id BIGINT NOT NULL,
  diagnosis_id BIGINT NULL,
  medication_id BIGINT NOT NULL,
  started_at DATE NOT NULL,
  ended_at DATE NULL,
  dose VARCHAR(120) NULL,
  doses_count SMALLINT NULL,
  route ENUM('IM','SC','IV','ORAL','TOPICAL','INTRAMAMMARY') NULL,
  withdrawal_milk_until DATE NULL,
  withdrawal_meat_until DATE NULL,
  cost DECIMAL(10,2) NULL,
  prescribed_by VARCHAR(160) NULL,
  vet_visit_id BIGINT NULL,
  created_by_user_id BIGINT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_treat_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_treat_animal FOREIGN KEY (animal_id) REFERENCES animal(id),
  CONSTRAINT fk_treat_diagnosis FOREIGN KEY (diagnosis_id) REFERENCES diagnosis(id),
  CONSTRAINT fk_treat_medication FOREIGN KEY (medication_id) REFERENCES medication(id),
  CONSTRAINT fk_treat_user FOREIGN KEY (created_by_user_id) REFERENCES app_user(id),
  CONSTRAINT fk_treat_visit FOREIGN KEY (vet_visit_id) REFERENCES vet_visit(id),
  INDEX ix_treat_acct_animal_date (account_id, animal_id, started_at),
  INDEX ix_treat_wd_milk (account_id, withdrawal_milk_until),
  INDEX ix_treat_wd_meat (account_id, withdrawal_meat_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pest_control (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  ranch_id BIGINT NULL,
  lot_id BIGINT NULL,
  pest_id BIGINT NOT NULL,
  product_used VARCHAR(200) NOT NULL,
  dose VARCHAR(120) NULL,
  applied_at DATE NOT NULL,
  next_application_at DATE NULL,
  cost DECIMAL(10,2) NULL,
  applied_by_user_id BIGINT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pc_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_pc_ranch FOREIGN KEY (ranch_id) REFERENCES ranch(id),
  CONSTRAINT fk_pc_lot FOREIGN KEY (lot_id) REFERENCES lot(id),
  CONSTRAINT fk_pc_pest FOREIGN KEY (pest_id) REFERENCES pest(id),
  CONSTRAINT fk_pc_user FOREIGN KEY (applied_by_user_id) REFERENCES app_user(id),
  INDEX ix_pc_acct_ranch_date (account_id, ranch_id, applied_at),
  INDEX ix_pc_acct_lot_date (account_id, lot_id, applied_at),
  INDEX ix_pc_next (account_id, next_application_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
